# Generated by Django 3.2.23 on 2023-11-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_bool',
            field=models.BooleanField(default=False),
        ),
    ]
