# Generated by Django 2.1.5 on 2024-05-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20240304_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active_member',
            field=models.BooleanField(default=False),
        ),
    ]
