# Generated by Django 2.1.5 on 2024-01-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20231228_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='GBM',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Industry',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Socials',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
