# Generated by Django 2.1.5 on 2023-12-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('Slides', models.URLField()),
                ('Desc', models.TextField()),
            ],
        ),
    ]
