# Generated by Django 2.1.5 on 2024-01-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='Semester',
            field=models.CharField(default='Fall', max_length=5),
            preserve_default=False,
        ),
    ]
