# Generated by Django 3.0.5 on 2024-08-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='campus',
            field=models.CharField(choices=[('Tempe', 'Tempe'), ('West', 'West'), ('Downtown', 'Downtown'), ('Poly', 'Poly'), ('Havasu', 'Havasu')], default='Tempe', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='discord',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_year',
            field=models.CharField(default='Freshman', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
