# Generated by Django 3.0.5 on 2024-08-17 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20240817_1114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fvent',
        ),
    ]
