# Generated by Django 3.0.5 on 2024-08-17 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_delete_fvent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetings',
            options={'verbose_name_plural': 'Meetings'},
        ),
        migrations.AlterModelOptions(
            name='signin',
            options={'verbose_name_plural': 'Signin'},
        ),
    ]
