# Generated by Django 3.0.5 on 2024-08-23 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20240817_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='flyer',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('1', 'GBM'), ('2', 'Social'), ('3', 'Industry Event'), ('4', 'Industry and GBM'), ('5', 'Social and GBM'), ('6', 'Social and Industry'), ('None', 'None')], default='None', max_length=20),
        ),
    ]
