# Generated by Django 3.0.5 on 2024-08-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20240823_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='flyer',
            field=models.ImageField(upload_to='static/Flyers/'),
        ),
    ]
