# Generated by Django 3.0.5 on 2024-08-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_auto_20240823_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='events',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
