# Generated by Django 3.2.23 on 2024-10-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_student_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('ASUID', models.CharField(max_length=10)),
                ('Socials', models.IntegerField(default=0)),
                ('GBM', models.IntegerField(default=0)),
                ('Industry', models.IntegerField(default=0)),
                ('graduation_year', models.CharField(max_length=50)),
                ('discord', models.CharField(max_length=50)),
                ('year', models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Final', 'Final'), ('Grad', 'Grad')], max_length=20)),
                ('major', models.CharField(max_length=100)),
                ('campus', models.CharField(choices=[('Tempe', 'Tempe'), ('West', 'West'), ('Downtown', 'Downtown'), ('Poly', 'Poly'), ('Havasu', 'Havasu')], max_length=50)),
                ('events', models.TextField()),
            ],
        ),
    ]
