# Generated by Django 5.1.3 on 2025-01-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='valid_profile',
            field=models.BooleanField(default=False),
        ),
    ]
