# Generated by Django 5.1.3 on 2025-01-19 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_tester_valid_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='valid_profile',
            new_name='validprofile',
        ),
        migrations.RenameField(
            model_name='tester',
            old_name='valid_profile',
            new_name='validprofile',
        ),
    ]
