# Generated by Django 5.1.3 on 2025-01-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_rename_valid_profile_student_validprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='campus',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='validprofile',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
