# Generated by Django 5.1.3 on 2025-03-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0013_student_volunteering_student_registration_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Not Made', max_length=200),
            preserve_default=False,
        ),
    ]
