# Generated by Django 5.1.3 on 2025-03-19 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0014_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_term', models.CharField(max_length=20)),
                ('current_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_attendance', to='meetings.event')),
                ('current_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_event', to='meetings.event')),
            ],
            options={
                'verbose_name_plural': 'Current',
            },
        ),
        migrations.RemoveField(
            model_name='signin',
            name='current',
        ),
        migrations.DeleteModel(
            name='Tester',
        ),
        migrations.DeleteModel(
            name='Signin',
        ),
    ]
