# Generated by Django 5.1.3 on 2025-03-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0015_current_remove_signin_current_delete_tester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('1', 'GBM'), ('2', 'Social'), ('3', 'Industry Event'), ('4', 'Industry and GBM'), ('5', 'Social and GBM'), ('6', 'Social and Industry'), ('7', 'Volunteering'), ('8', 'Workshop'), ('None', 'None')], default='None', max_length=20),
        ),
    ]
