# Generated by Django 5.1.3 on 2025-04-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0016_alter_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registration_payment',
        ),
        migrations.AddField(
            model_name='student',
            name='grad_year_last2',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
