# Generated by Django 5.1.2 on 2025-04-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0016_alter_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('ASUID', models.CharField(max_length=10)),
                ('paid_dues', models.BooleanField(blank=True)),
                ('active_date_start', models.DateTimeField(blank=True, null=True)),
                ('active_date_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='registration_payment',
        ),
    ]
