# Generated by Django 5.1.3 on 2025-04-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0017_remove_student_registration_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grad_year_last2',
        ),
    ]
